title: OLI COURT
author: Oli Court
email: ocourt14@googlemail.com
description: > # this means to ignore newlines until "baseurl:"
  A portfolio of published prose and articles by Oli Court

# social links
twitter_username: AnotherOli

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
